<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>




<html>

<head>

<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<script type="text/javascript">
	function viewDetails(modalid) {
		$(modelid).modal('toggle');

	}
</script>


<%-- <c:url value='/previewOilReport-${oilReport.id}' /> --%>


<title>Energy Meters</title>
</head>

<body onload="myFunction()" style="margin: 0;">
	<%@include file="../authheader.jsp"%>
	<div class="sticky-top">
		<nav aria-label="breadcrumb" class="sticky-top">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href="javascript:window.location='home'">Home</a></li>

				<li class="breadcrumb-item active" aria-current="page">File
					Master</li>
			</ol>
		</nav>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {

			$('.modal-content').resizable({
				//alsoResize: ".modal-dialog",
				minHeight : 300,
				minWidth : 600
			});
			$('.modal-dialog').draggable();
		});
	</script>





	<div class="container-fluid">
		<span class="lead">File generated by energy meters <c:if
				test="${not empty reportMonthYearDate}">in the month of <fmt:formatDate
					value="${reportMonthYearDate}" pattern="MMM,yyyy" />
			</c:if></span>
		<div class="card"></div>
		<div class="table-responsive">


			<table class="table table-striped table-bordered table-hover">
				<tr>
					<th>Sr. No</th>
					<th>ProcessingStatus</th>
					<th>Location</th>
					<th>Meter</th>


					<th>File Generation Date Time</th>

				<th>FileName</th>
				<th>Uploaded By</th>
				</tr>
				<c:forEach items="${fileModel.filesUploadedDetail}"
					var="fileDetails" varStatus="indexStatus">

					<%@include file="fileDetailsStatusSnippet.jsp"%>
					<td>
						Substation:${fileDetails.location.substationMaster.stationName}

						Division:${fileDetails.location.divisionMaster.divisionname}
						Circle:${fileDetails.location.circleMaster.circleName}</td>
					<td>Meter
						Location:${fileDetails.location.feederName} Boundary
						Type:${fileDetails.location.boundaryTypeMaster.boundaryType}
						${fileDetails.location.locationId} Meter Details(Sr No:
						${fileDetails.meterMaster.meterSrNo})(Make:${fileDetails.meterMaster.meterType})


					</td>


					<td><fmt:formatDate value="${fileDetails.transactionDate}"
							pattern="dd/MM/yyyy HH:mm:ss" /></td>

					<td>${fileDetails.userfileName }</td>
					<td>${fileDetails.uploadedBy.userNameLabel }</td>
					
					
				</c:forEach>
			</table>



		</div>
	</div>

	



</body>
</html>