<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>



<html>

<head>
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<script type="text/javascript">
	function viewDetails(modalid) {
		$(modelid).modal('toggle');

	}
</script>

<%-- <c:url value='/previewOilReport-${oilReport.id}' /> --%>


<title>Energy Meters</title>
</head>

<body    style="margin: 0;">

	
	<script type="text/javascript">
		$(document).ready(function() {

			$('.modal-content').resizable({
				//alsoResize: ".modal-dialog",
				minHeight : 300,
				minWidth : 600
			});
			$('.modal-dialog').draggable();
		});
	</script>





	<div class="container-fluid">
		<span class="lead">File generated by energy meters <c:if
				test="${not empty reportMonthYearDate}">in the month of <fmt:formatDate
					value="${reportMonthYearDate}" pattern="MMM,yyyy" />
			</c:if></span>
		<div class="card">
		
		<div class="container">

	
	


</div>
		</div>
		<div class="table-responsive">


			<table class="table table-striped table-bordered table-hover">
				<tr>
					<th>Sr. No</th>
					<th>ProcessingStatus</th>
					<th>Location</th>
					<th>Meter</th>


					<th>File Generation Date Time</th>

					<th>No. of Daily(24 hr) Records</th>
					<th>No. of Load Survey(15 min) Records in File</th>


					<th>Actions</th>
					<th>FileName</th>
				</tr>
				<c:forEach items="${fileModel.filesUploadedDetail}"
					var="fileDetails" varStatus="indexStatus">

					<%@include file="fileDetailsStatusSnippet.jsp"%>
					<td>
						Substation:${fileDetails.location.substationMaster.stationName}

						Division:${fileDetails.location.divisionMaster.divisionname}
						Circle:${fileDetails.location.circleMaster.circleName}</td>
					<td>Meter
						Location:${fileDetails.location.feederName} Boundary
						Type:${fileDetails.location.boundaryTypeMaster.boundaryType}
						${fileDetails.location.locationId} Meter Details(Sr No:
						${fileDetails.meterMaster.meterSrNo})(Make:${fileDetails.meterMaster.meterType})


					</td>


					<td><fmt:formatDate value="${fileDetails.transactionDate}"
							pattern="dd/MM/yyyy HH:mm:ss" /></td>

					<td>${fileDetails.dailyRecordCount}</td>
					<td>${fileDetails.surveyRecordCount}</td>

					<td><%@include file="fileDetailsActionSnippet.jsp"%>
					</td>
					<td>${fileDetails.userfileName }</td>
				</c:forEach>
			</table>



		</div>
	</div>




</body>
</html>