<%@page import="org.pstcl.ea.util.EAUtil"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="sec"
	uri="http://www.springframework.org/security/tags"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>


<html>

<head>

<c:set var="ctx" value="${pageContext.servletContext.contextPath}" />
<script type="text/javascript">
	function connect() {

		var socket = new SockJS('${ctx}/gs-guide-websocket');
		stompClient = Stomp.over(socket);
		stompClient.connect({}, function(frame) {
			setConnected(true);
			console.log('Connected: ' + frame);
			stompClient.subscribe('/topic/fileUploadingStatus', function(
					greeting) {
				showGreeting(JSON.parse(greeting.body).content);
			});
		});
	}

	var stompClient = null;

	function setConnected(connected) {

		if (connected) {
			$("#conversation").show();
		} else {
			$("#conversation").hide();
		}
		$("#greetings").html("");
	}

	function disconnect() {
		if (stompClient !== null) {
			stompClient.disconnect();
		}
		setConnected(false);
		console.log("Disconnected");
	}

	function sendName() {
		stompClient.send("/app/hello", {}, JSON.stringify({
			'name' : $("#name").val()
		}));
	}

	function showGreeting(message) {

		//$("<tr><td>prependTo</td></tr>").prependTo("table > tbody");
		$("#greetings").prepend("<tr><td>" + new Date() + "</td><td>" + message + "</td></tr>");
		$("<tr><td>" + message + "</td></tr>").insertBefore('"#greetings" > tr:first');
	}
</script>


<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<script type="text/javascript">
	function saveOrUpdate() {
		document.forms['saveDailyTxForm'].submit();
	}

</script>

<%-- <c:url value='/previewOilReport-${oilReport.id}' /> --%>


<title>Energy Meters</title>
</head>

<body    style="margin: 0;">
	<%@include file="authheader.jsp"%>
	<div class="sticky-top">
		<nav aria-label="breadcrumb" class="sticky-top">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a
					href="javascript:window.location='home'">Home</a></li>

				<li class="breadcrumb-item active" aria-current="page">Upload
					File(s)</li>
			</ol>
		</nav>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {

			connect();
			
		});
	</script>
	<script type="text/javascript">
		$(function() {
			$('.date-picker').datepicker({
				yearRange : '2018:2020',
				changeMonth : true,
				changeYear : true,
				showButtonPanel : false,
				dateFormat : "dd/mm/yy"

			});
		});
	</script>

	<div class="container-fluid">
		<c:if test="${not empty success}">
			<div class="alert alert-success lead">${success}</div>
		</c:if>
		<span class="lead">Upload CMRI File</span>

		<div class="table-responsive">


			<form:form method="POST"
				action="uploadMultiZip?${_csrf.parameterName}=${_csrf.token}"
				modelAttribute="fileModel" enctype="multipart/form-data">
				<table>
					<tr>
						<td colspan="2"><span> <i class="fa fa-warning"
								style="font-size: 18px; color: red;"><i
									class="fas fa-exclamation-circle"></i>Please Upload files generated by the CRMI device only.
									System will not accept any other .zip file.
									</i>
						</span></td>
					</tr>
					<tr>
						<td><label>Select files to upload</label></td>

						<td><input type="file" name="files" accept="application/zip"
							multiple="multiple" /></td>
					</tr>
					<tr>
						<td><input type="submit" value="Upload" /></td>
					</tr>
				</table>


			</form:form>


		</div>
	</div>


<noscript>
	<h2 style="color: #ff0000">Seems your browser doesn't support
		Javascript! Websocket relies on Javascript being enabled. Please
		enable Javascript and reload this page!</h2>
</noscript>
<div class="container">

	
	<div id="main-content" class="container">
		
		<div class="row">
			<div class="col-md-12">
				<table id="conversation" class="table table-striped">
					<thead>
						<tr>
							<th><span class="lead">File uploading status will appear here</span> </th>
						</tr>
					</thead>
					<tbody id="greetings">
					</tbody>
				</table>
			</div>
		</div>
	</div>



</div>
</body>
</html>